//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Client.UI.MensajeriaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Mensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEnvioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioDestinoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameDestinoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEnvio {
            get {
                return this.FechaEnvioField;
            }
            set {
                if ((this.FechaEnvioField.Equals(value) != true)) {
                    this.FechaEnvioField = value;
                    this.RaisePropertyChanged("FechaEnvio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioDestino {
            get {
                return this.IdUsuarioDestinoField;
            }
            set {
                if ((this.IdUsuarioDestinoField.Equals(value) != true)) {
                    this.IdUsuarioDestinoField = value;
                    this.RaisePropertyChanged("IdUsuarioDestino");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsernameDestino {
            get {
                return this.UsernameDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameDestinoField, value) != true)) {
                    this.UsernameDestinoField = value;
                    this.RaisePropertyChanged("UsernameDestino");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MensajeriaService.IMensajeriaService", CallbackContract=typeof(DamasChinas_Client.UI.MensajeriaService.IMensajeriaServiceCallback))]
    public interface IMensajeriaService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMensajeriaService/EnviarMensaje")]
        void EnviarMensaje(DamasChinas_Client.UI.MensajeriaService.Mensaje mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMensajeriaService/EnviarMensaje")]
        System.Threading.Tasks.Task EnviarMensajeAsync(DamasChinas_Client.UI.MensajeriaService.Mensaje mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMensajeriaService/RegistrarCliente")]
        void RegistrarCliente(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMensajeriaService/RegistrarCliente")]
        System.Threading.Tasks.Task RegistrarClienteAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajeriaService/ObtenerHistorialMensajes", ReplyAction="http://tempuri.org/IMensajeriaService/ObtenerHistorialMensajesResponse")]
        DamasChinas_Client.UI.MensajeriaService.Mensaje[] ObtenerHistorialMensajes(int idUsuarioCliente, string usernameDestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajeriaService/ObtenerHistorialMensajes", ReplyAction="http://tempuri.org/IMensajeriaService/ObtenerHistorialMensajesResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.MensajeriaService.Mensaje[]> ObtenerHistorialMensajesAsync(int idUsuarioCliente, string usernameDestino);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMensajeriaServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMensajeriaService/RecibirMensaje")]
        void RecibirMensaje(DamasChinas_Client.UI.MensajeriaService.Mensaje mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMensajeriaServiceChannel : DamasChinas_Client.UI.MensajeriaService.IMensajeriaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MensajeriaServiceClient : System.ServiceModel.DuplexClientBase<DamasChinas_Client.UI.MensajeriaService.IMensajeriaService>, DamasChinas_Client.UI.MensajeriaService.IMensajeriaService {
        
        public MensajeriaServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MensajeriaServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MensajeriaServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MensajeriaServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MensajeriaServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void EnviarMensaje(DamasChinas_Client.UI.MensajeriaService.Mensaje mensaje) {
            base.Channel.EnviarMensaje(mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeAsync(DamasChinas_Client.UI.MensajeriaService.Mensaje mensaje) {
            return base.Channel.EnviarMensajeAsync(mensaje);
        }
        
        public void RegistrarCliente(string username) {
            base.Channel.RegistrarCliente(username);
        }
        
        public System.Threading.Tasks.Task RegistrarClienteAsync(string username) {
            return base.Channel.RegistrarClienteAsync(username);
        }
        
        public DamasChinas_Client.UI.MensajeriaService.Mensaje[] ObtenerHistorialMensajes(int idUsuarioCliente, string usernameDestino) {
            return base.Channel.ObtenerHistorialMensajes(idUsuarioCliente, usernameDestino);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.MensajeriaService.Mensaje[]> ObtenerHistorialMensajesAsync(int idUsuarioCliente, string usernameDestino) {
            return base.Channel.ObtenerHistorialMensajesAsync(idUsuarioCliente, usernameDestino);
        }
    }
}
