//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Client.UI.AccountManagerServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublicProfile", Namespace="http://schemas.datacontract.org/2004/07/Damas_Chinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class PublicProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocialUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialUrl {
            get {
                return this.SocialUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SocialUrlField, value) != true)) {
                    this.SocialUrlField = value;
                    this.RaisePropertyChanged("SocialUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/Damas_Chinas_Server.Contracts")]
    [System.SerializableAttribute()]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.AccountManagerServiceProxy.MessageCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechnicalDetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.AccountManagerServiceProxy.MessageCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnicalDetail {
            get {
                return this.TechnicalDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicalDetailField, value) != true)) {
                    this.TechnicalDetailField = value;
                    this.RaisePropertyChanged("TechnicalDetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/Damas_Chinas_Server.Common")]
    public enum MessageCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginInvalidCredentials = 1001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserDuplicateEmail = 1002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 1003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreationFailed = 1100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerUnavailable = 2001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NetworkLatency = 2100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownError = 9999,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountManagerServiceProxy.IAccountManager")]
    public interface IAccountManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/GetPublicProfile", ReplyAction="http://tempuri.org/IAccountManager/GetPublicProfileResponse")]
        DamasChinas_Client.UI.AccountManagerServiceProxy.PublicProfile GetPublicProfile(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/GetPublicProfile", ReplyAction="http://tempuri.org/IAccountManager/GetPublicProfileResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.AccountManagerServiceProxy.PublicProfile> GetPublicProfileAsync(int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/ChangeUsername", ReplyAction="http://tempuri.org/IAccountManager/ChangeUsernameResponse")]
        DamasChinas_Client.UI.AccountManagerServiceProxy.OperationResult ChangeUsername(string username, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/ChangeUsername", ReplyAction="http://tempuri.org/IAccountManager/ChangeUsernameResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.AccountManagerServiceProxy.OperationResult> ChangeUsernameAsync(string username, string newUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/ChangePassword", ReplyAction="http://tempuri.org/IAccountManager/ChangePasswordResponse")]
        DamasChinas_Client.UI.AccountManagerServiceProxy.OperationResult ChangePassword(string correo, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountManager/ChangePassword", ReplyAction="http://tempuri.org/IAccountManager/ChangePasswordResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.AccountManagerServiceProxy.OperationResult> ChangePasswordAsync(string correo, string newPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountManagerChannel : DamasChinas_Client.UI.AccountManagerServiceProxy.IAccountManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountManagerClient : System.ServiceModel.ClientBase<DamasChinas_Client.UI.AccountManagerServiceProxy.IAccountManager>, DamasChinas_Client.UI.AccountManagerServiceProxy.IAccountManager {
        
        public AccountManagerClient() {
        }
        
        public AccountManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DamasChinas_Client.UI.AccountManagerServiceProxy.PublicProfile GetPublicProfile(int idUser) {
            return base.Channel.GetPublicProfile(idUser);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.AccountManagerServiceProxy.PublicProfile> GetPublicProfileAsync(int idUser) {
            return base.Channel.GetPublicProfileAsync(idUser);
        }
        
        public DamasChinas_Client.UI.AccountManagerServiceProxy.OperationResult ChangeUsername(string username, string newUsername) {
            return base.Channel.ChangeUsername(username, newUsername);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.AccountManagerServiceProxy.OperationResult> ChangeUsernameAsync(string username, string newUsername) {
            return base.Channel.ChangeUsernameAsync(username, newUsername);
        }
        
        public DamasChinas_Client.UI.AccountManagerServiceProxy.OperationResult ChangePassword(string correo, string newPassword) {
            return base.Channel.ChangePassword(correo, newPassword);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.AccountManagerServiceProxy.OperationResult> ChangePasswordAsync(string correo, string newPassword) {
            return base.Channel.ChangePasswordAsync(correo, newPassword);
        }
    }
}
