//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Client.UI.MatchServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Contracts")]
    [System.SerializableAttribute()]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.MatchServiceProxy.MessageCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechnicalDetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.MatchServiceProxy.MessageCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnicalDetail {
            get {
                return this.TechnicalDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicalDetailField, value) != true)) {
                    this.TechnicalDetailField = value;
                    this.RaisePropertyChanged("TechnicalDetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
    public enum MessageCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AvatarUpdateSuccess = 5002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CodeSentSuccessfully = 3014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginInvalidCredentials = 1001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserDuplicateEmail = 1002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 1003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserValidationError = 1201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeNotFound = 1202,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeExpired = 1203,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeInvalid = 1204,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeSendError = 1205,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreationFailed = 1100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 1101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInactive = 1102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyUserBanned = 1103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyClosed = 1104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 1105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyAlreadyInLobby = 1106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInvalidMaxPlayers = 1107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotHost = 1108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyGameAlreadyStarted = 1109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyMinPlayersNotReached = 1110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyPlayerAlreadyReported = 1111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyStartFailed = 1112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInvitationFailed = 1113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInvitationTargetNotOnline = 1114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyKicked = 1115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendRequestAlreadyPending = 3200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyFriends = 3201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerUnavailable = 2001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMove = 2002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RankingUnavailable = 2003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NetworkLatency = 2100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownError = 9999,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyCredentials = 3001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordsDontMatch = 3002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 3003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameEmpty = 3004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserProfileNotFound = 3005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendsLoadError = 3006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmail = 3007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FieldLengthExceeded = 3008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChatOpenError = 3009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NavigationError = 3010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameEmpty = 3100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameLength = 3101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameCharacters = 3102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsernameEmpty = 3110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsernameLength = 3111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsernameCharacters = 3112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameExists = 3113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordEmpty = 3120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordLength = 3121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordUppercase = 3122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordLowercase = 3123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordDigit = 3124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordSpecial = 3125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailEmpty = 3130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailTooLong = 3131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 3132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserBlocked = 3202,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPieceInOrigin = 4000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DestinationCellOccupied = 4001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateOutsideBoard = 4002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchFinished = 4003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerNotInMatch = 4004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotPlayersTurn = 4005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginCellInvalid = 4006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginCellNotPlayersPiece = 4007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PathCellRepeated = 4008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DestinationOutsideBoard = 4009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidStep = 4011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultistepRequiresJump = 4012,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdjacentMoveSingleStep = 4013,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPieceToJump = 4014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultistepMustHaveJump = 4015,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPlayerCount = 4016,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerColorDuplicate = 4017,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerTargetZoneMissing = 4018,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CellAlreadyOccupied = 4019,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CellHasNoPiece = 4020,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCubeCoordinate = 4021,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidHalfCoordinate = 4022,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerIdRequired = 4023,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerNameRequired = 4024,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RepositoryUsernameEmpty = 4027,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RepositoryUserNotFound = 4028,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AvatarUpdateFailed = 5001,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MoveRequestDto", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class MoveRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.MatchServiceProxy.HexCoordinateDto DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.MatchServiceProxy.HexCoordinateDto OriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.MatchServiceProxy.HexCoordinateDto Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((this.LobbyCodeField.Equals(value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.MatchServiceProxy.HexCoordinateDto Origin {
            get {
                return this.OriginField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginField, value) != true)) {
                    this.OriginField = value;
                    this.RaisePropertyChanged("Origin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HexCoordinateDto", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class HexCoordinateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Z {
            get {
                return this.ZField;
            }
            set {
                if ((this.ZField.Equals(value) != true)) {
                    this.ZField = value;
                    this.RaisePropertyChanged("Z");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchStateDto", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class MatchStateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, DamasChinas_Client.UI.MatchServiceProxy.HexCoordinateDto[]> BoardPiecesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentTurnPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, DamasChinas_Client.UI.MatchServiceProxy.HexCoordinateDto[]> BoardPieces {
            get {
                return this.BoardPiecesField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardPiecesField, value) != true)) {
                    this.BoardPiecesField = value;
                    this.RaisePropertyChanged("BoardPieces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentTurnPlayer {
            get {
                return this.CurrentTurnPlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentTurnPlayerField, value) != true)) {
                    this.CurrentTurnPlayerField = value;
                    this.RaisePropertyChanged("CurrentTurnPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TurnChangeDto", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class TurnChangeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.MatchServiceProxy.MatchStateDto BoardStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.MatchServiceProxy.HexCoordinateDto MoveDestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.MatchServiceProxy.HexCoordinateDto MoveOriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NextPlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviousPlayerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.MatchServiceProxy.MatchStateDto BoardState {
            get {
                return this.BoardStateField;
            }
            set {
                if ((object.ReferenceEquals(this.BoardStateField, value) != true)) {
                    this.BoardStateField = value;
                    this.RaisePropertyChanged("BoardState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.MatchServiceProxy.HexCoordinateDto MoveDestination {
            get {
                return this.MoveDestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.MoveDestinationField, value) != true)) {
                    this.MoveDestinationField = value;
                    this.RaisePropertyChanged("MoveDestination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.MatchServiceProxy.HexCoordinateDto MoveOrigin {
            get {
                return this.MoveOriginField;
            }
            set {
                if ((object.ReferenceEquals(this.MoveOriginField, value) != true)) {
                    this.MoveOriginField = value;
                    this.RaisePropertyChanged("MoveOrigin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextPlayer {
            get {
                return this.NextPlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.NextPlayerField, value) != true)) {
                    this.NextPlayerField = value;
                    this.RaisePropertyChanged("NextPlayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviousPlayer {
            get {
                return this.PreviousPlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviousPlayerField, value) != true)) {
                    this.PreviousPlayerField = value;
                    this.RaisePropertyChanged("PreviousPlayer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchServiceProxy.IMatchService", CallbackContract=typeof(DamasChinas_Client.UI.MatchServiceProxy.IMatchServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IMatchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/ConnectToMatch", ReplyAction="http://tempuri.org/IMatchService/ConnectToMatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.MatchServiceProxy.MessageCode), Action="http://tempuri.org/IMatchService/ConnectToMatchMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.MatchServiceProxy.OperationResult ConnectToMatch(int lobbyCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/ConnectToMatch", ReplyAction="http://tempuri.org/IMatchService/ConnectToMatchResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.MatchServiceProxy.OperationResult> ConnectToMatchAsync(int lobbyCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/MovePiece", ReplyAction="http://tempuri.org/IMatchService/MovePieceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.MatchServiceProxy.MessageCode), Action="http://tempuri.org/IMatchService/MovePieceMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.MatchServiceProxy.OperationResult MovePiece(DamasChinas_Client.UI.MatchServiceProxy.MoveRequestDto move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/MovePiece", ReplyAction="http://tempuri.org/IMatchService/MovePieceResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.MatchServiceProxy.OperationResult> MovePieceAsync(DamasChinas_Client.UI.MatchServiceProxy.MoveRequestDto move);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/LeaveMatch", ReplyAction="http://tempuri.org/IMatchService/LeaveMatchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.MatchServiceProxy.MessageCode), Action="http://tempuri.org/IMatchService/LeaveMatchMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        void LeaveMatch(int lobbyCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/LeaveMatch", ReplyAction="http://tempuri.org/IMatchService/LeaveMatchResponse")]
        System.Threading.Tasks.Task LeaveMatchAsync(int lobbyCode, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetMatchState", ReplyAction="http://tempuri.org/IMatchService/GetMatchStateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.MatchServiceProxy.MessageCode), Action="http://tempuri.org/IMatchService/GetMatchStateMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.MatchServiceProxy.MatchStateDto GetMatchState(int lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchService/GetMatchState", ReplyAction="http://tempuri.org/IMatchService/GetMatchStateResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.MatchServiceProxy.MatchStateDto> GetMatchStateAsync(int lobbyCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnPlayerMoved")]
        void OnPlayerMoved(DamasChinas_Client.UI.MatchServiceProxy.TurnChangeDto turnInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnMatchEnded")]
        void OnMatchEnded(string winnerUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnPlayerLeftMatch")]
        void OnPlayerLeftMatch(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMatchService/OnErrorOccurred")]
        void OnErrorOccurred(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchServiceChannel : DamasChinas_Client.UI.MatchServiceProxy.IMatchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchServiceClient : System.ServiceModel.DuplexClientBase<DamasChinas_Client.UI.MatchServiceProxy.IMatchService>, DamasChinas_Client.UI.MatchServiceProxy.IMatchService {
        
        public MatchServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MatchServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MatchServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MatchServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public DamasChinas_Client.UI.MatchServiceProxy.OperationResult ConnectToMatch(int lobbyCode, string username) {
            return base.Channel.ConnectToMatch(lobbyCode, username);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.MatchServiceProxy.OperationResult> ConnectToMatchAsync(int lobbyCode, string username) {
            return base.Channel.ConnectToMatchAsync(lobbyCode, username);
        }
        
        public DamasChinas_Client.UI.MatchServiceProxy.OperationResult MovePiece(DamasChinas_Client.UI.MatchServiceProxy.MoveRequestDto move) {
            return base.Channel.MovePiece(move);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.MatchServiceProxy.OperationResult> MovePieceAsync(DamasChinas_Client.UI.MatchServiceProxy.MoveRequestDto move) {
            return base.Channel.MovePieceAsync(move);
        }
        
        public void LeaveMatch(int lobbyCode, string username) {
            base.Channel.LeaveMatch(lobbyCode, username);
        }
        
        public System.Threading.Tasks.Task LeaveMatchAsync(int lobbyCode, string username) {
            return base.Channel.LeaveMatchAsync(lobbyCode, username);
        }
        
        public DamasChinas_Client.UI.MatchServiceProxy.MatchStateDto GetMatchState(int lobbyCode) {
            return base.Channel.GetMatchState(lobbyCode);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.MatchServiceProxy.MatchStateDto> GetMatchStateAsync(int lobbyCode) {
            return base.Channel.GetMatchStateAsync(lobbyCode);
        }
    }
}
