//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Client.UI.RankingServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RankingEntry", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class RankingEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LosesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchesPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WinRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarFile {
            get {
                return this.AvatarFileField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarFileField, value) != true)) {
                    this.AvatarFileField = value;
                    this.RaisePropertyChanged("AvatarFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Loses {
            get {
                return this.LosesField;
            }
            set {
                if ((this.LosesField.Equals(value) != true)) {
                    this.LosesField = value;
                    this.RaisePropertyChanged("Loses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchesPlayed {
            get {
                return this.MatchesPlayedField;
            }
            set {
                if ((this.MatchesPlayedField.Equals(value) != true)) {
                    this.MatchesPlayedField = value;
                    this.RaisePropertyChanged("MatchesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WinRate {
            get {
                return this.WinRateField;
            }
            set {
                if ((this.WinRateField.Equals(value) != true)) {
                    this.WinRateField = value;
                    this.RaisePropertyChanged("WinRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins {
            get {
                return this.WinsField;
            }
            set {
                if ((this.WinsField.Equals(value) != true)) {
                    this.WinsField = value;
                    this.RaisePropertyChanged("Wins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
    public enum MessageCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AvatarUpdateSuccess = 5002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CodeSentSuccessfully = 3014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginInvalidCredentials = 1001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserDuplicateEmail = 1002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 1003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserValidationError = 1201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeNotFound = 1202,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeExpired = 1203,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeInvalid = 1204,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeSendError = 1205,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreationFailed = 1100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 1101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInactive = 1102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyUserBanned = 1103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyClosed = 1104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 1105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyAlreadyInLobby = 1106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInvalidMaxPlayers = 1107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotHost = 1108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyGameAlreadyStarted = 1109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyMinPlayersNotReached = 1110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyPlayerAlreadyReported = 1111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyStartFailed = 1112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInvitationFailed = 1113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInvitationTargetNotOnline = 1114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyKicked = 1115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendRequestAlreadyPending = 3200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyFriends = 3201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerUnavailable = 2001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMove = 2002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RankingUnavailable = 2003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseUnavailable = 2004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseValidationFailed = 2005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseUpdateFailed = 2006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseConnectionLost = 2007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseSqlTimeout = 2008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseConfigurationMissing = 2009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseAuthenticationFailed = 2010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NetworkLatency = 2100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownError = 9999,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyCredentials = 3001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordsDontMatch = 3002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 3003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameEmpty = 3004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserProfileNotFound = 3005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendsLoadError = 3006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmail = 3007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FieldLengthExceeded = 3008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChatOpenError = 3009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NavigationError = 3010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameEmpty = 3100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameLength = 3101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameCharacters = 3102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsernameEmpty = 3110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsernameLength = 3111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsernameCharacters = 3112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameExists = 3113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordEmpty = 3120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordLength = 3121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordUppercase = 3122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordLowercase = 3123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordDigit = 3124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordSpecial = 3125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailEmpty = 3130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailTooLong = 3131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 3132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserBlocked = 3202,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPieceInOrigin = 4000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DestinationCellOccupied = 4001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateOutsideBoard = 4002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchFinished = 4003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerNotInMatch = 4004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotPlayersTurn = 4005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginCellInvalid = 4006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginCellNotPlayersPiece = 4007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PathCellRepeated = 4008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DestinationOutsideBoard = 4009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidStep = 4011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultistepRequiresJump = 4012,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdjacentMoveSingleStep = 4013,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPieceToJump = 4014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultistepMustHaveJump = 4015,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPlayerCount = 4016,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerColorDuplicate = 4017,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerTargetZoneMissing = 4018,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CellAlreadyOccupied = 4019,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CellHasNoPiece = 4020,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCubeCoordinate = 4021,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidHalfCoordinate = 4022,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerIdRequired = 4023,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerNameRequired = 4024,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RepositoryUsernameEmpty = 4027,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RepositoryUserNotFound = 4028,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerUnavailabless = 7070,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerTemporarilyDisconnected = 4030,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerReconnected = 4031,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerRemovedAfterDisconnect = 4032,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AvatarUpdateFailed = 5001,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RankingServiceProxy.IRankingService")]
    public interface IRankingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRankingService/GetTop10Ranking", ReplyAction="http://tempuri.org/IRankingService/GetTop10RankingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.RankingServiceProxy.MessageCode), Action="http://tempuri.org/IRankingService/GetTop10RankingMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.RankingServiceProxy.RankingEntry[] GetTop10Ranking();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRankingService/GetTop10Ranking", ReplyAction="http://tempuri.org/IRankingService/GetTop10RankingResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.RankingServiceProxy.RankingEntry[]> GetTop10RankingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRankingServiceChannel : DamasChinas_Client.UI.RankingServiceProxy.IRankingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RankingServiceClient : System.ServiceModel.ClientBase<DamasChinas_Client.UI.RankingServiceProxy.IRankingService>, DamasChinas_Client.UI.RankingServiceProxy.IRankingService {
        
        public RankingServiceClient() {
        }
        
        public RankingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RankingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RankingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RankingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DamasChinas_Client.UI.RankingServiceProxy.RankingEntry[] GetTop10Ranking() {
            return base.Channel.GetTop10Ranking();
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.RankingServiceProxy.RankingEntry[]> GetTop10RankingAsync() {
            return base.Channel.GetTop10RankingAsync();
        }
    }
}
