//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Client.UI.GuestSessionServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GuestSessionServiceProxy.IGuestSessionService", CallbackContract=typeof(DamasChinas_Client.UI.GuestSessionServiceProxy.IGuestSessionServiceCallback))]
    public interface IGuestSessionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestSessionService/Subscribe", ReplyAction="http://tempuri.org/IGuestSessionService/SubscribeResponse")]
        void Subscribe(string guestUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestSessionService/Subscribe", ReplyAction="http://tempuri.org/IGuestSessionService/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync(string guestUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestSessionService/Unsubscribe", ReplyAction="http://tempuri.org/IGuestSessionService/UnsubscribeResponse")]
        void Unsubscribe(string guestUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGuestSessionService/Unsubscribe", ReplyAction="http://tempuri.org/IGuestSessionService/UnsubscribeResponse")]
        System.Threading.Tasks.Task UnsubscribeAsync(string guestUsername);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuestSessionServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGuestSessionService/OnServerMessage")]
        void OnServerMessage(string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGuestSessionServiceChannel : DamasChinas_Client.UI.GuestSessionServiceProxy.IGuestSessionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuestSessionServiceClient : System.ServiceModel.DuplexClientBase<DamasChinas_Client.UI.GuestSessionServiceProxy.IGuestSessionService>, DamasChinas_Client.UI.GuestSessionServiceProxy.IGuestSessionService {
        
        public GuestSessionServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GuestSessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GuestSessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GuestSessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GuestSessionServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe(string guestUsername) {
            base.Channel.Subscribe(guestUsername);
        }
        
        public System.Threading.Tasks.Task SubscribeAsync(string guestUsername) {
            return base.Channel.SubscribeAsync(guestUsername);
        }
        
        public void Unsubscribe(string guestUsername) {
            base.Channel.Unsubscribe(guestUsername);
        }
        
        public System.Threading.Tasks.Task UnsubscribeAsync(string guestUsername) {
            return base.Channel.UnsubscribeAsync(guestUsername);
        }
    }
}
