//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Client.UI.LobbyServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbySummaryDto", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class LobbySummaryDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.LobbyServiceProxy.LobbyVisibility VisibilityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPlayers {
            get {
                return this.CurrentPlayersField;
            }
            set {
                if ((this.CurrentPlayersField.Equals(value) != true)) {
                    this.CurrentPlayersField = value;
                    this.RaisePropertyChanged("CurrentPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostUsername {
            get {
                return this.HostUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostUsernameField, value) != true)) {
                    this.HostUsernameField = value;
                    this.RaisePropertyChanged("HostUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((this.LobbyCodeField.Equals(value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxPlayers {
            get {
                return this.MaxPlayersField;
            }
            set {
                if ((this.MaxPlayersField.Equals(value) != true)) {
                    this.MaxPlayersField = value;
                    this.RaisePropertyChanged("MaxPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.LobbyServiceProxy.LobbyVisibility Visibility {
            get {
                return this.VisibilityField;
            }
            set {
                if ((this.VisibilityField.Equals(value) != true)) {
                    this.VisibilityField = value;
                    this.RaisePropertyChanged("Visibility");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyVisibility", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    public enum LobbyVisibility : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Public = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Private = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
    public enum MessageCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AvatarUpdateSuccess = 5002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CodeSentSuccessfully = 3014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginInvalidCredentials = 1001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserDuplicateEmail = 1002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 1003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserValidationError = 1201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeNotFound = 1202,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeExpired = 1203,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeInvalid = 1204,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeSendError = 1205,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreationFailed = 1100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 1101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInactive = 1102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyUserBanned = 1103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyClosed = 1104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 1105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyAlreadyInLobby = 1106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInvalidMaxPlayers = 1107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotHost = 1108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyGameAlreadyStarted = 1109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyMinPlayersNotReached = 1110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyPlayerAlreadyReported = 1111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyStartFailed = 1112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInvitationFailed = 1113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInvitationTargetNotOnline = 1114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyKicked = 1115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendRequestAlreadyPending = 3200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyFriends = 3201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerUnavailable = 2001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMove = 2002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RankingUnavailable = 2003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseUnavailable = 2004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseValidationFailed = 2005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseUpdateFailed = 2006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseConnectionLost = 2007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseSqlTimeout = 2008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseConfigurationMissing = 2009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseAuthenticationFailed = 2010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NetworkLatency = 2100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownError = 9999,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyCredentials = 3001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordsDontMatch = 3002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 3003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameEmpty = 3004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserProfileNotFound = 3005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendsLoadError = 3006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmail = 3007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FieldLengthExceeded = 3008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChatOpenError = 3009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NavigationError = 3010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameEmpty = 3100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameLength = 3101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameCharacters = 3102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsernameEmpty = 3110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsernameLength = 3111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsernameCharacters = 3112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameExists = 3113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordEmpty = 3120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordLength = 3121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordUppercase = 3122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordLowercase = 3123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordDigit = 3124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordSpecial = 3125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailEmpty = 3130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailTooLong = 3131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 3132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserBlocked = 3202,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPieceInOrigin = 4000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DestinationCellOccupied = 4001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CoordinateOutsideBoard = 4002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchFinished = 4003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerNotInMatch = 4004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotPlayersTurn = 4005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginCellInvalid = 4006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OriginCellNotPlayersPiece = 4007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PathCellRepeated = 4008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DestinationOutsideBoard = 4009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidStep = 4011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultistepRequiresJump = 4012,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AdjacentMoveSingleStep = 4013,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPieceToJump = 4014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MultistepMustHaveJump = 4015,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPlayerCount = 4016,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerColorDuplicate = 4017,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerTargetZoneMissing = 4018,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CellAlreadyOccupied = 4019,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CellHasNoPiece = 4020,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCubeCoordinate = 4021,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidHalfCoordinate = 4022,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerIdRequired = 4023,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerNameRequired = 4024,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RepositoryUsernameEmpty = 4027,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RepositoryUserNotFound = 4028,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerUnavailabless = 7070,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerTemporarilyDisconnected = 4030,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerReconnected = 4031,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PlayerRemovedAfterDisconnect = 4032,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AvatarUpdateFailed = 5001,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbySnapshotDto", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class LobbySnapshotDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGameStartedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.LobbyServiceProxy.LobbyMemberDto[] MembersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.LobbyServiceProxy.LobbyVisibility VisibilityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGameStarted {
            get {
                return this.IsGameStartedField;
            }
            set {
                if ((this.IsGameStartedField.Equals(value) != true)) {
                    this.IsGameStartedField = value;
                    this.RaisePropertyChanged("IsGameStarted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((this.LobbyCodeField.Equals(value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxPlayers {
            get {
                return this.MaxPlayersField;
            }
            set {
                if ((this.MaxPlayersField.Equals(value) != true)) {
                    this.MaxPlayersField = value;
                    this.RaisePropertyChanged("MaxPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.LobbyServiceProxy.LobbyMemberDto[] Members {
            get {
                return this.MembersField;
            }
            set {
                if ((object.ReferenceEquals(this.MembersField, value) != true)) {
                    this.MembersField = value;
                    this.RaisePropertyChanged("Members");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.LobbyServiceProxy.LobbyVisibility Visibility {
            get {
                return this.VisibilityField;
            }
            set {
                if ((this.VisibilityField.Equals(value) != true)) {
                    this.VisibilityField = value;
                    this.RaisePropertyChanged("Visibility");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyMemberDto", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class LobbyMemberDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarFile {
            get {
                return this.AvatarFileField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarFileField, value) != true)) {
                    this.AvatarFileField = value;
                    this.RaisePropertyChanged("AvatarFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHost {
            get {
                return this.IsHostField;
            }
            set {
                if ((this.IsHostField.Equals(value) != true)) {
                    this.IsHostField = value;
                    this.RaisePropertyChanged("IsHost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateLobbyRequest", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class CreateLobbyRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxPlayersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.LobbyServiceProxy.LobbyVisibility VisibilityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxPlayers {
            get {
                return this.MaxPlayersField;
            }
            set {
                if ((this.MaxPlayersField.Equals(value) != true)) {
                    this.MaxPlayersField = value;
                    this.RaisePropertyChanged("MaxPlayers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.LobbyServiceProxy.LobbyVisibility Visibility {
            get {
                return this.VisibilityField;
            }
            set {
                if ((this.VisibilityField.Equals(value) != true)) {
                    this.VisibilityField = value;
                    this.RaisePropertyChanged("Visibility");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Contracts")]
    [System.SerializableAttribute()]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.LobbyServiceProxy.MessageCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechnicalDetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.LobbyServiceProxy.MessageCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnicalDetail {
            get {
                return this.TechnicalDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicalDetailField, value) != true)) {
                    this.TechnicalDetailField = value;
                    this.RaisePropertyChanged("TechnicalDetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JoinLobbyRequest", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class JoinLobbyRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((this.LobbyCodeField.Equals(value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LobbyInvitationDto", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class LobbyInvitationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LobbyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxPlayersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostUsername {
            get {
                return this.HostUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostUsernameField, value) != true)) {
                    this.HostUsernameField = value;
                    this.RaisePropertyChanged("HostUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LobbyCode {
            get {
                return this.LobbyCodeField;
            }
            set {
                if ((this.LobbyCodeField.Equals(value) != true)) {
                    this.LobbyCodeField = value;
                    this.RaisePropertyChanged("LobbyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxPlayers {
            get {
                return this.MaxPlayersField;
            }
            set {
                if ((this.MaxPlayersField.Equals(value) != true)) {
                    this.MaxPlayersField = value;
                    this.RaisePropertyChanged("MaxPlayers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LobbyServiceProxy.ILobbyService", CallbackContract=typeof(DamasChinas_Client.UI.LobbyServiceProxy.ILobbyServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ILobbyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetPublicLobbies", ReplyAction="http://tempuri.org/ILobbyService/GetPublicLobbiesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode), Action="http://tempuri.org/ILobbyService/GetPublicLobbiesMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.LobbyServiceProxy.LobbySummaryDto[] GetPublicLobbies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetPublicLobbies", ReplyAction="http://tempuri.org/ILobbyService/GetPublicLobbiesResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.LobbySummaryDto[]> GetPublicLobbiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetCurrentLobby", ReplyAction="http://tempuri.org/ILobbyService/GetCurrentLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode), Action="http://tempuri.org/ILobbyService/GetCurrentLobbyMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.LobbyServiceProxy.LobbySnapshotDto GetCurrentLobby(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetCurrentLobby", ReplyAction="http://tempuri.org/ILobbyService/GetCurrentLobbyResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.LobbySnapshotDto> GetCurrentLobbyAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/CreateLobby", ReplyAction="http://tempuri.org/ILobbyService/CreateLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode), Action="http://tempuri.org/ILobbyService/CreateLobbyMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.LobbyServiceProxy.OperationResult CreateLobby(string hostUsername, DamasChinas_Client.UI.LobbyServiceProxy.CreateLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/CreateLobby", ReplyAction="http://tempuri.org/ILobbyService/CreateLobbyResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> CreateLobbyAsync(string hostUsername, DamasChinas_Client.UI.LobbyServiceProxy.CreateLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/JoinLobby", ReplyAction="http://tempuri.org/ILobbyService/JoinLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode), Action="http://tempuri.org/ILobbyService/JoinLobbyMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.LobbyServiceProxy.OperationResult JoinLobby(DamasChinas_Client.UI.LobbyServiceProxy.JoinLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/JoinLobby", ReplyAction="http://tempuri.org/ILobbyService/JoinLobbyResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> JoinLobbyAsync(DamasChinas_Client.UI.LobbyServiceProxy.JoinLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/LeaveLobby", ReplyAction="http://tempuri.org/ILobbyService/LeaveLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode), Action="http://tempuri.org/ILobbyService/LeaveLobbyMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.LobbyServiceProxy.OperationResult LeaveLobby(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/LeaveLobby", ReplyAction="http://tempuri.org/ILobbyService/LeaveLobbyResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> LeaveLobbyAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/StartGame", ReplyAction="http://tempuri.org/ILobbyService/StartGameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode), Action="http://tempuri.org/ILobbyService/StartGameMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.LobbyServiceProxy.OperationResult StartGame(string hostUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/StartGame", ReplyAction="http://tempuri.org/ILobbyService/StartGameResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> StartGameAsync(string hostUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/KickPlayer", ReplyAction="http://tempuri.org/ILobbyService/KickPlayerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode), Action="http://tempuri.org/ILobbyService/KickPlayerMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.LobbyServiceProxy.OperationResult KickPlayer(string hostUsername, int lobbyCode, string targetUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/KickPlayer", ReplyAction="http://tempuri.org/ILobbyService/KickPlayerResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> KickPlayerAsync(string hostUsername, int lobbyCode, string targetUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/ReportPlayer", ReplyAction="http://tempuri.org/ILobbyService/ReportPlayerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode), Action="http://tempuri.org/ILobbyService/ReportPlayerMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.LobbyServiceProxy.OperationResult ReportPlayer(DamasChinas_Shared.Contracts.Dtos.ReportPlayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/ReportPlayer", ReplyAction="http://tempuri.org/ILobbyService/ReportPlayerResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> ReportPlayerAsync(DamasChinas_Shared.Contracts.Dtos.ReportPlayerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetBanInfo", ReplyAction="http://tempuri.org/ILobbyService/GetBanInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode), Action="http://tempuri.org/ILobbyService/GetBanInfoMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Shared.Contracts.Dtos.BanInfoDto GetBanInfo(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/GetBanInfo", ReplyAction="http://tempuri.org/ILobbyService/GetBanInfoResponse")]
        System.Threading.Tasks.Task<DamasChinas_Shared.Contracts.Dtos.BanInfoDto> GetBanInfoAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/InviteFriend", ReplyAction="http://tempuri.org/ILobbyService/InviteFriendResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode), Action="http://tempuri.org/ILobbyService/InviteFriendMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.LobbyServiceProxy.OperationResult InviteFriend(string hostUsername, string friendUsername, int lobbyCode, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/InviteFriend", ReplyAction="http://tempuri.org/ILobbyService/InviteFriendResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> InviteFriendAsync(string hostUsername, string friendUsername, int lobbyCode, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyService/SendLobbyMessage")]
        void SendLobbyMessage(string sender, int lobbyCode, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyService/SendLobbyMessage")]
        System.Threading.Tasks.Task SendLobbyMessageAsync(string sender, int lobbyCode, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/JoinLobbyGuest", ReplyAction="http://tempuri.org/ILobbyService/JoinLobbyGuestResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode), Action="http://tempuri.org/ILobbyService/JoinLobbyGuestMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.LobbyServiceProxy.OperationResult JoinLobbyGuest(DamasChinas_Client.UI.LobbyServiceProxy.JoinLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/JoinLobbyGuest", ReplyAction="http://tempuri.org/ILobbyService/JoinLobbyGuestResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> JoinLobbyGuestAsync(DamasChinas_Client.UI.LobbyServiceProxy.JoinLobbyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/ReconnectToLobby", ReplyAction="http://tempuri.org/ILobbyService/ReconnectToLobbyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode), Action="http://tempuri.org/ILobbyService/ReconnectToLobbyMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.LobbyServiceProxy.OperationResult ReconnectToLobby(string username, int lobbyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILobbyService/ReconnectToLobby", ReplyAction="http://tempuri.org/ILobbyService/ReconnectToLobbyResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> ReconnectToLobbyAsync(string username, int lobbyCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyService/OnLobbySnapshot")]
        void OnLobbySnapshot(DamasChinas_Client.UI.LobbyServiceProxy.LobbySnapshotDto snapshot);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyService/OnLobbyClosed")]
        void OnLobbyClosed(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode reason);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyService/OnGameStarting")]
        void OnGameStarting();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyService/OnInvitationReceived")]
        void OnInvitationReceived(DamasChinas_Client.UI.LobbyServiceProxy.LobbyInvitationDto invitation);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyService/OnKickedFromLobby")]
        void OnKickedFromLobby(DamasChinas_Client.UI.LobbyServiceProxy.MessageCode reason);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyService/OnBanStatusUpdated")]
        void OnBanStatusUpdated(DamasChinas_Shared.Contracts.Dtos.BanInfoDto banInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILobbyService/OnChatMessageReceived")]
        void OnChatMessageReceived(string sender, string message, string timestamp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILobbyServiceChannel : DamasChinas_Client.UI.LobbyServiceProxy.ILobbyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LobbyServiceClient : System.ServiceModel.DuplexClientBase<DamasChinas_Client.UI.LobbyServiceProxy.ILobbyService>, DamasChinas_Client.UI.LobbyServiceProxy.ILobbyService {
        
        public LobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public LobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public LobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public LobbyServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public DamasChinas_Client.UI.LobbyServiceProxy.LobbySummaryDto[] GetPublicLobbies() {
            return base.Channel.GetPublicLobbies();
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.LobbySummaryDto[]> GetPublicLobbiesAsync() {
            return base.Channel.GetPublicLobbiesAsync();
        }
        
        public DamasChinas_Client.UI.LobbyServiceProxy.LobbySnapshotDto GetCurrentLobby(string username) {
            return base.Channel.GetCurrentLobby(username);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.LobbySnapshotDto> GetCurrentLobbyAsync(string username) {
            return base.Channel.GetCurrentLobbyAsync(username);
        }
        
        public DamasChinas_Client.UI.LobbyServiceProxy.OperationResult CreateLobby(string hostUsername, DamasChinas_Client.UI.LobbyServiceProxy.CreateLobbyRequest request) {
            return base.Channel.CreateLobby(hostUsername, request);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> CreateLobbyAsync(string hostUsername, DamasChinas_Client.UI.LobbyServiceProxy.CreateLobbyRequest request) {
            return base.Channel.CreateLobbyAsync(hostUsername, request);
        }
        
        public DamasChinas_Client.UI.LobbyServiceProxy.OperationResult JoinLobby(DamasChinas_Client.UI.LobbyServiceProxy.JoinLobbyRequest request) {
            return base.Channel.JoinLobby(request);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> JoinLobbyAsync(DamasChinas_Client.UI.LobbyServiceProxy.JoinLobbyRequest request) {
            return base.Channel.JoinLobbyAsync(request);
        }
        
        public DamasChinas_Client.UI.LobbyServiceProxy.OperationResult LeaveLobby(string username) {
            return base.Channel.LeaveLobby(username);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> LeaveLobbyAsync(string username) {
            return base.Channel.LeaveLobbyAsync(username);
        }
        
        public DamasChinas_Client.UI.LobbyServiceProxy.OperationResult StartGame(string hostUsername) {
            return base.Channel.StartGame(hostUsername);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> StartGameAsync(string hostUsername) {
            return base.Channel.StartGameAsync(hostUsername);
        }
        
        public DamasChinas_Client.UI.LobbyServiceProxy.OperationResult KickPlayer(string hostUsername, int lobbyCode, string targetUsername) {
            return base.Channel.KickPlayer(hostUsername, lobbyCode, targetUsername);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> KickPlayerAsync(string hostUsername, int lobbyCode, string targetUsername) {
            return base.Channel.KickPlayerAsync(hostUsername, lobbyCode, targetUsername);
        }
        
        public DamasChinas_Client.UI.LobbyServiceProxy.OperationResult ReportPlayer(DamasChinas_Shared.Contracts.Dtos.ReportPlayerRequest request) {
            return base.Channel.ReportPlayer(request);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> ReportPlayerAsync(DamasChinas_Shared.Contracts.Dtos.ReportPlayerRequest request) {
            return base.Channel.ReportPlayerAsync(request);
        }
        
        public DamasChinas_Shared.Contracts.Dtos.BanInfoDto GetBanInfo(string username) {
            return base.Channel.GetBanInfo(username);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Shared.Contracts.Dtos.BanInfoDto> GetBanInfoAsync(string username) {
            return base.Channel.GetBanInfoAsync(username);
        }
        
        public DamasChinas_Client.UI.LobbyServiceProxy.OperationResult InviteFriend(string hostUsername, string friendUsername, int lobbyCode, string languageCode) {
            return base.Channel.InviteFriend(hostUsername, friendUsername, lobbyCode, languageCode);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> InviteFriendAsync(string hostUsername, string friendUsername, int lobbyCode, string languageCode) {
            return base.Channel.InviteFriendAsync(hostUsername, friendUsername, lobbyCode, languageCode);
        }
        
        public void SendLobbyMessage(string sender, int lobbyCode, string message) {
            base.Channel.SendLobbyMessage(sender, lobbyCode, message);
        }
        
        public System.Threading.Tasks.Task SendLobbyMessageAsync(string sender, int lobbyCode, string message) {
            return base.Channel.SendLobbyMessageAsync(sender, lobbyCode, message);
        }
        
        public DamasChinas_Client.UI.LobbyServiceProxy.OperationResult JoinLobbyGuest(DamasChinas_Client.UI.LobbyServiceProxy.JoinLobbyRequest request) {
            return base.Channel.JoinLobbyGuest(request);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> JoinLobbyGuestAsync(DamasChinas_Client.UI.LobbyServiceProxy.JoinLobbyRequest request) {
            return base.Channel.JoinLobbyGuestAsync(request);
        }
        
        public DamasChinas_Client.UI.LobbyServiceProxy.OperationResult ReconnectToLobby(string username, int lobbyCode) {
            return base.Channel.ReconnectToLobby(username, lobbyCode);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.LobbyServiceProxy.OperationResult> ReconnectToLobbyAsync(string username, int lobbyCode) {
            return base.Channel.ReconnectToLobbyAsync(username, lobbyCode);
        }
    }
}
