//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Client.UI.FriendServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendDto", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class FriendDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ConnectionStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Avatar {
            get {
                return this.AvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarField, value) != true)) {
                    this.AvatarField = value;
                    this.RaisePropertyChanged("Avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ConnectionState {
            get {
                return this.ConnectionStateField;
            }
            set {
                if ((this.ConnectionStateField.Equals(value) != true)) {
                    this.ConnectionStateField = value;
                    this.RaisePropertyChanged("ConnectionState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
    public enum MessageCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AvatarUpdateSuccess = 5002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CodeSentSuccessfully = 3014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginInvalidCredentials = 1001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserDuplicateEmail = 1002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 1003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserValidationError = 1201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeNotFound = 1202,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeExpired = 1203,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeInvalid = 1204,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VerificationCodeSendError = 1205,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchCreationFailed = 1100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotFound = 1101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInactive = 1102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyUserBanned = 1103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyClosed = 1104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyFull = 1105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyAlreadyInLobby = 1106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInvalidMaxPlayers = 1107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyNotHost = 1108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyGameAlreadyStarted = 1109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyMinPlayersNotReached = 1110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyPlayerAlreadyReported = 1111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyStartFailed = 1112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInvitationFailed = 1113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyInvitationTargetNotOnline = 1114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LobbyKicked = 1115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendRequestAlreadyPending = 3200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AlreadyFriends = 3201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerUnavailable = 2001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidMove = 2002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RankingUnavailable = 2003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NetworkLatency = 2100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnknownError = 9999,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyCredentials = 3001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordsDontMatch = 3002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 3003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameEmpty = 3004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserProfileNotFound = 3005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FriendsLoadError = 3006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmail = 3007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FieldLengthExceeded = 3008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChatOpenError = 3009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NavigationError = 3010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameEmpty = 3100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameLength = 3101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidNameCharacters = 3102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsernameEmpty = 3110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsernameLength = 3111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUsernameCharacters = 3112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameExists = 3113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordEmpty = 3120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordLength = 3121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordUppercase = 3122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordLowercase = 3123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordDigit = 3124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPasswordSpecial = 3125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailEmpty = 3130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailTooLong = 3131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 3132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AvatarUpdateFailed = 5001,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PublicFriendProfile", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Dtos")]
    [System.SerializableAttribute()]
    public partial class PublicFriendProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvatarFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LosesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchesPlayedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SocialUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvatarFile {
            get {
                return this.AvatarFileField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarFileField, value) != true)) {
                    this.AvatarFileField = value;
                    this.RaisePropertyChanged("AvatarFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Loses {
            get {
                return this.LosesField;
            }
            set {
                if ((this.LosesField.Equals(value) != true)) {
                    this.LosesField = value;
                    this.RaisePropertyChanged("Loses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchesPlayed {
            get {
                return this.MatchesPlayedField;
            }
            set {
                if ((this.MatchesPlayedField.Equals(value) != true)) {
                    this.MatchesPlayedField = value;
                    this.RaisePropertyChanged("MatchesPlayed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SocialUrl {
            get {
                return this.SocialUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SocialUrlField, value) != true)) {
                    this.SocialUrlField = value;
                    this.RaisePropertyChanged("SocialUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Wins {
            get {
                return this.WinsField;
            }
            set {
                if ((this.WinsField.Equals(value) != true)) {
                    this.WinsField = value;
                    this.RaisePropertyChanged("Wins");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Contracts")]
    [System.SerializableAttribute()]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DamasChinas_Client.UI.FriendServiceProxy.MessageCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TechnicalDetailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DamasChinas_Client.UI.FriendServiceProxy.MessageCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TechnicalDetail {
            get {
                return this.TechnicalDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.TechnicalDetailField, value) != true)) {
                    this.TechnicalDetailField = value;
                    this.RaisePropertyChanged("TechnicalDetail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FriendServiceProxy.IFriendService", CallbackContract=typeof(DamasChinas_Client.UI.FriendServiceProxy.IFriendServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IFriendService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendService/SubscribeFriendEvents")]
        void SubscribeFriendEvents(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendService/SubscribeFriendEvents")]
        System.Threading.Tasks.Task SubscribeFriendEventsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendService/UnsubscribeFriendEvents")]
        void UnsubscribeFriendEvents(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendService/UnsubscribeFriendEvents")]
        System.Threading.Tasks.Task UnsubscribeFriendEventsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriends", ReplyAction="http://tempuri.org/IFriendService/GetFriendsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.FriendServiceProxy.MessageCode), Action="http://tempuri.org/IFriendService/GetFriendsMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.FriendServiceProxy.FriendDto[] GetFriends(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriends", ReplyAction="http://tempuri.org/IFriendService/GetFriendsResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.FriendDto[]> GetFriendsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriendRequests", ReplyAction="http://tempuri.org/IFriendService/GetFriendRequestsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.FriendServiceProxy.MessageCode), Action="http://tempuri.org/IFriendService/GetFriendRequestsMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.FriendServiceProxy.FriendDto[] GetFriendRequests(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriendRequests", ReplyAction="http://tempuri.org/IFriendService/GetFriendRequestsResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.FriendDto[]> GetFriendRequestsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriendPublicProfile", ReplyAction="http://tempuri.org/IFriendService/GetFriendPublicProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DamasChinas_Client.UI.FriendServiceProxy.MessageCode), Action="http://tempuri.org/IFriendService/GetFriendPublicProfileMessageCodeFault", Name="MessageCode", Namespace="http://schemas.datacontract.org/2004/07/DamasChinas_Server.Common")]
        DamasChinas_Client.UI.FriendServiceProxy.PublicFriendProfile GetFriendPublicProfile(string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/GetFriendPublicProfile", ReplyAction="http://tempuri.org/IFriendService/GetFriendPublicProfileResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.PublicFriendProfile> GetFriendPublicProfileAsync(string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendService/SendFriendRequestResponse")]
        DamasChinas_Client.UI.FriendServiceProxy.OperationResult SendFriendRequest(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/SendFriendRequest", ReplyAction="http://tempuri.org/IFriendService/SendFriendRequestResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.OperationResult> SendFriendRequestAsync(string senderUsername, string receiverUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/DeleteFriend", ReplyAction="http://tempuri.org/IFriendService/DeleteFriendResponse")]
        DamasChinas_Client.UI.FriendServiceProxy.OperationResult DeleteFriend(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/DeleteFriend", ReplyAction="http://tempuri.org/IFriendService/DeleteFriendResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.OperationResult> DeleteFriendAsync(string username, string friendUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/UpdateBlockStatus", ReplyAction="http://tempuri.org/IFriendService/UpdateBlockStatusResponse")]
        DamasChinas_Client.UI.FriendServiceProxy.OperationResult UpdateBlockStatus(string blockerUsername, string blockedUsername, bool block);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/UpdateBlockStatus", ReplyAction="http://tempuri.org/IFriendService/UpdateBlockStatusResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.OperationResult> UpdateBlockStatusAsync(string blockerUsername, string blockedUsername, bool block);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/UpdateFriendRequestStatus", ReplyAction="http://tempuri.org/IFriendService/UpdateFriendRequestStatusResponse")]
        DamasChinas_Client.UI.FriendServiceProxy.OperationResult UpdateFriendRequestStatus(string receiverUsername, string senderUsername, bool accept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/UpdateFriendRequestStatus", ReplyAction="http://tempuri.org/IFriendService/UpdateFriendRequestStatusResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.OperationResult> UpdateFriendRequestStatusAsync(string receiverUsername, string senderUsername, bool accept);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/DeleteFriendAndBlock", ReplyAction="http://tempuri.org/IFriendService/DeleteFriendAndBlockResponse")]
        DamasChinas_Client.UI.FriendServiceProxy.OperationResult DeleteFriendAndBlock(string blockerUsername, string blockedUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFriendService/DeleteFriendAndBlock", ReplyAction="http://tempuri.org/IFriendService/DeleteFriendAndBlockResponse")]
        System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.OperationResult> DeleteFriendAndBlockAsync(string blockerUsername, string blockedUsername);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendService/FriendRequestReceived")]
        void FriendRequestReceived(string fromUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendService/FriendRequestAccepted")]
        void FriendRequestAccepted(string byUsername);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendService/FriendRemoved")]
        void FriendRemoved(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendService/UserBlockedYou")]
        void UserBlockedYou(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendService/UserUnblockedYou")]
        void UserUnblockedYou(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IFriendService/FriendListUpdated")]
        void FriendListUpdated();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFriendServiceChannel : DamasChinas_Client.UI.FriendServiceProxy.IFriendService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FriendServiceClient : System.ServiceModel.DuplexClientBase<DamasChinas_Client.UI.FriendServiceProxy.IFriendService>, DamasChinas_Client.UI.FriendServiceProxy.IFriendService {
        
        public FriendServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public FriendServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public FriendServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FriendServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public FriendServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SubscribeFriendEvents(string username) {
            base.Channel.SubscribeFriendEvents(username);
        }
        
        public System.Threading.Tasks.Task SubscribeFriendEventsAsync(string username) {
            return base.Channel.SubscribeFriendEventsAsync(username);
        }
        
        public void UnsubscribeFriendEvents(string username) {
            base.Channel.UnsubscribeFriendEvents(username);
        }
        
        public System.Threading.Tasks.Task UnsubscribeFriendEventsAsync(string username) {
            return base.Channel.UnsubscribeFriendEventsAsync(username);
        }
        
        public DamasChinas_Client.UI.FriendServiceProxy.FriendDto[] GetFriends(string username) {
            return base.Channel.GetFriends(username);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.FriendDto[]> GetFriendsAsync(string username) {
            return base.Channel.GetFriendsAsync(username);
        }
        
        public DamasChinas_Client.UI.FriendServiceProxy.FriendDto[] GetFriendRequests(string username) {
            return base.Channel.GetFriendRequests(username);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.FriendDto[]> GetFriendRequestsAsync(string username) {
            return base.Channel.GetFriendRequestsAsync(username);
        }
        
        public DamasChinas_Client.UI.FriendServiceProxy.PublicFriendProfile GetFriendPublicProfile(string friendUsername) {
            return base.Channel.GetFriendPublicProfile(friendUsername);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.PublicFriendProfile> GetFriendPublicProfileAsync(string friendUsername) {
            return base.Channel.GetFriendPublicProfileAsync(friendUsername);
        }
        
        public DamasChinas_Client.UI.FriendServiceProxy.OperationResult SendFriendRequest(string senderUsername, string receiverUsername) {
            return base.Channel.SendFriendRequest(senderUsername, receiverUsername);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.OperationResult> SendFriendRequestAsync(string senderUsername, string receiverUsername) {
            return base.Channel.SendFriendRequestAsync(senderUsername, receiverUsername);
        }
        
        public DamasChinas_Client.UI.FriendServiceProxy.OperationResult DeleteFriend(string username, string friendUsername) {
            return base.Channel.DeleteFriend(username, friendUsername);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.OperationResult> DeleteFriendAsync(string username, string friendUsername) {
            return base.Channel.DeleteFriendAsync(username, friendUsername);
        }
        
        public DamasChinas_Client.UI.FriendServiceProxy.OperationResult UpdateBlockStatus(string blockerUsername, string blockedUsername, bool block) {
            return base.Channel.UpdateBlockStatus(blockerUsername, blockedUsername, block);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.OperationResult> UpdateBlockStatusAsync(string blockerUsername, string blockedUsername, bool block) {
            return base.Channel.UpdateBlockStatusAsync(blockerUsername, blockedUsername, block);
        }
        
        public DamasChinas_Client.UI.FriendServiceProxy.OperationResult UpdateFriendRequestStatus(string receiverUsername, string senderUsername, bool accept) {
            return base.Channel.UpdateFriendRequestStatus(receiverUsername, senderUsername, accept);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.OperationResult> UpdateFriendRequestStatusAsync(string receiverUsername, string senderUsername, bool accept) {
            return base.Channel.UpdateFriendRequestStatusAsync(receiverUsername, senderUsername, accept);
        }
        
        public DamasChinas_Client.UI.FriendServiceProxy.OperationResult DeleteFriendAndBlock(string blockerUsername, string blockedUsername) {
            return base.Channel.DeleteFriendAndBlock(blockerUsername, blockedUsername);
        }
        
        public System.Threading.Tasks.Task<DamasChinas_Client.UI.FriendServiceProxy.OperationResult> DeleteFriendAndBlockAsync(string blockerUsername, string blockedUsername) {
            return base.Channel.DeleteFriendAndBlockAsync(blockerUsername, blockedUsername);
        }
    }
}
