title: "Documentación Damas Chinas"
description: "Docs con GitHub Pages + AsciiDoc"
markdown: kramdown
theme: jekyll-theme-cayman

plugins:
  - jekyll-asciidoc

asciidoctor:
  safe: unsafe
  attributes:
    icons: font
    toc: left
    toclevels: 3
    sectanchors: true
    source-highlighter: rouge
