//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Damas_Chinas_Server
{
	using System;
	using System.Collections.Generic;

	public partial class usuarios
	{
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public usuarios()
		{
			this.amistades = new HashSet<amistades>();
			this.amistades1 = new HashSet<amistades>();
			this.bloqueos = new HashSet<bloqueos>();
			this.bloqueos1 = new HashSet<bloqueos>();
			this.participantes_partida = new HashSet<participantes_partida>();
			this.perfiles = new HashSet<perfiles>();
			this.solicitudes_amistad = new HashSet<solicitudes_amistad>();
			this.solicitudes_amistad1 = new HashSet<solicitudes_amistad>();
			this.mensajes = new HashSet<mensajes>();
			this.mensajes1 = new HashSet<mensajes>();
		}

		public int id_usuario { get; set; }
		public string correo { get; set; }
		public string password_hash { get; set; }
		public string rol { get; set; }
		public System.DateTime fecha_creacion { get; set; }

		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<amistades> amistades { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<amistades> amistades1 { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<bloqueos> bloqueos { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<bloqueos> bloqueos1 { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<participantes_partida> participantes_partida { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<perfiles> perfiles { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<solicitudes_amistad> solicitudes_amistad { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<solicitudes_amistad> solicitudes_amistad1 { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<mensajes> mensajes { get; set; }
		[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<mensajes> mensajes1 { get; set; }
	}
}
