//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamasChinas_Client.UI.UsuarioServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuarioServiceReference.IUsuarioService", CallbackContract=typeof(DamasChinas_Client.UI.UsuarioServiceReference.IUsuarioServiceCallback))]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarioService/CrearUsuarioResponse")]
        void CrearUsuario(string nombre, string apellido, string correo, string password, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/CrearUsuario", ReplyAction="http://tempuri.org/IUsuarioService/CrearUsuarioResponse")]
        System.Threading.Tasks.Task CrearUsuarioAsync(string nombre, string apellido, string correo, string password, string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/UsuarioCreado", ReplyAction="http://tempuri.org/IUsuarioService/UsuarioCreadoResponse")]
        void UsuarioCreado(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioService/ErrorCreandoUsuario", ReplyAction="http://tempuri.org/IUsuarioService/ErrorCreandoUsuarioResponse")]
        void ErrorCreandoUsuario(string mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : DamasChinas_Client.UI.UsuarioServiceReference.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.DuplexClientBase<DamasChinas_Client.UI.UsuarioServiceReference.IUsuarioService>, DamasChinas_Client.UI.UsuarioServiceReference.IUsuarioService {
        
        public UsuarioServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void CrearUsuario(string nombre, string apellido, string correo, string password, string username) {
            base.Channel.CrearUsuario(nombre, apellido, correo, password, username);
        }
        
        public System.Threading.Tasks.Task CrearUsuarioAsync(string nombre, string apellido, string correo, string password, string username) {
            return base.Channel.CrearUsuarioAsync(nombre, apellido, correo, password, username);
        }
    }
}
